source "http://rubygems.org"
gemspec

gem "rspec-rails"
gem "capybara"
gem "shoulda-matchers"
gem "sqlite3"
gem "poltergeist"
gem "jasmine"

gem "annoyance", path: "../../gems/annoyance"
gem "email_signup", path: "../email_signup"
gem "event_counter", path: "../event_counter"
