source "http://rubygems.org"
gemspec

gem 'jasmine-core', github: 'pivotal/jasmine'
gem 'jasmine', github: 'pivotal/jasmine-gem'

gem "annoyance", path: "../../domain/annoyance"
gem "email_signup", path: "../email_signup"
